---
- name: Install Zabbix Agent
  hosts: all
  become: true
  vars:
    zabbix_server: 84.252.140.56
  tasks:
    - name: Install prerequisites (CentOS)
      package:
        name: epel-release
        state: present
      when: ansible_distribution == 'CentOS'
    - name: Install prerequisites (Ubuntu)
      package:
        name: wget
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Install Zabbix Agent (CentOS)
      package:
        name: 'https://repo.zabbix.com/zabbix/5.4/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-agent-5.4.12-1.el7.{{ ansible_architecture }}.rpm'
        state: present
      when: ansible_distribution == 'CentOS'
    - name: Install Zabbix Agent (Ubuntu)
      apt:
        deb: 'https://repo.zabbix.com/zabbix/5.4/ubuntu/pool/main/z/zabbix/zabbix-agent_5.4.12-1+ubuntu{{ ansible_distribution_version }}_{{ "amd64" if ansible_architecture == "x86_64" else "i386" }}.deb'
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Install Zabbix Agent package
      package:
        name: 'zabbix-agent'
        state: present
    - name: Configure Zabbix Agent
      template:
        src: /etc/ansible/common/files/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: '0644'
      notify: Start and enable
  handlers:
  - name: Start and enable
    systemd:
      name: zabbix-agent.service
      enabled: yes
      state: started
